[profile.default]
evm_version = "shanghai"       # See https://www.evmdiff.com/features?name=PUSH0&kind=opcode
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
test = "test"
cache_path = "cache_forge"
optimizer = true
optimizer_runs = 10_000
solc_version = "0.8.21"
build_info = true
extra_output = ["storageLayout"]
sender = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
sparse_mode = true

[profile.ci]
fuzz = { runs = 10_000 }
verbosity = 4

[fmt]
bracket_spacing = false
int_types = "long"
line_length = 120
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[rpc_endpoints]
localhost = "http://localhost:8545"
